Repository sofastack/sofa-dashboard, pull requests merged in 2019-08, with the labels that each got.

#35 optimized-service-console
  sofa-dashboard-backend/sofa-dashboard-core/src/main/java/com/alipay/sofa/dashboard/model/ServiceAppModel.java
  sofa-dashboard-backend/sofa-dashboard-governance/src/main/java/com/alipay/sofa/dashboard/listener/zookeeper/ConsumerNodeChangeListener.java
  sofa-dashboard-backend/sofa-dashboard-governance/src/main/java/com/alipay/sofa/dashboard/listener/zookeeper/ProviderNodeChangeListener.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/ServiceManageController.java
  sofa-dashboard-backend/sofa-dashboard-web/src/test/java/com/alipay/sofa/dashboard/ServiceManageControllerTest.java
Labels: enhancement

#38 Use redis storage docking dashboard function
  pom.xml
  sofa-dashboard-backend/pom.xml
  sofa-dashboard-backend/sofa-dashboard-application/pom.xml
  sofa-dashboard-backend/sofa-dashboard-application/src/main/java/com/alipay/sofa/dashboard/app/AppServiceImpl.java
  sofa-dashboard-backend/sofa-dashboard-application/src/main/java/com/alipay/sofa/dashboard/app/MonitorServiceImpl.java
  sofa-dashboard-backend/sofa-dashboard-application/src/main/java/com/alipay/sofa/dashboard/application/ApplicationService.java
  sofa-dashboard-backend/sofa-dashboard-application/src/main/java/com/alipay/sofa/dashboard/application/ZookeeperApplicationManager.java
  sofa-dashboard-backend/sofa-dashboard-application/src/test/java/com/alipay/sofa/dashboard/app/AppServiceTest.java
  sofa-dashboard-backend/sofa-dashboard-application/src/test/java/com/alipay/sofa/dashboard/app/MonitorServiceTest.java
  sofa-dashboard-backend/sofa-dashboard-application/src/test/java/com/alipay/sofa/dashboard/mock/MockRegistry.java
  sofa-dashboard-backend/sofa-dashboard-application/src/test/java/com/alipay/sofa/dashboard/mock/MockStore.java
  sofa-dashboard-backend/sofa-dashboard-arkmng/src/main/java/com/alipay/sofa/dashboard/impl/ZkCommandPushManager.java
  sofa-dashboard-backend/sofa-dashboard-arkmng/src/main/java/com/alipay/sofa/dashboard/impl/ZkHelper.java
  sofa-dashboard-backend/sofa-dashboard-core/pom.xml
  sofa-dashboard-backend/sofa-dashboard-core/src/main/java/com/alipay/sofa/dashboard/model/AppInfo.java
  sofa-dashboard-backend/sofa-dashboard-core/src/main/java/com/alipay/sofa/dashboard/model/ApplicationInfo.java
  sofa-dashboard-backend/sofa-dashboard-core/src/main/java/com/alipay/sofa/dashboard/model/StampedValueEntity.java
  sofa-dashboard-backend/sofa-dashboard-core/src/main/java/com/alipay/sofa/dashboard/spi/AppService.java
  sofa-dashboard-backend/sofa-dashboard-core/src/main/java/com/alipay/sofa/dashboard/spi/ApplicationManager.java
  sofa-dashboard-backend/sofa-dashboard-core/src/main/java/com/alipay/sofa/dashboard/spi/MonitorService.java
  sofa-dashboard-backend/sofa-dashboard-web/pom.xml
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/configuration/CorsConfiguration.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/ApplicationController.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/ArkAppMngController.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/ArkMngController.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/InstanceController.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/ServiceManageController.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/model/InstanceRecord.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/model/RecordResponse.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/model/TreeNode.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/utils/HostPortUtils.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/utils/MapUtils.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/utils/TreeNodeConverter.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/vo/ApplicationVO.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/resources/application-localhost.properties
  sofa-dashboard-backend/sofa-dashboard-web/src/test/java/com/alipay/sofa/dashboard/ApplicationControllerTest.java
Labels: cla:yes, size/XXL

#40 Adapt the simplified front-end interface
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/InstanceController.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/utils/TreeNodeConverter.java
Labels: cla:yes, enhancement, size/M

#42 Fix that the application should not be displayed if the number of instances is 0
  .gitignore
  sofa-dashboard-backend/sofa-dashboard-application/src/main/java/com/alipay/sofa/dashboard/app/AppServiceImpl.java
  sofa-dashboard-backend/sofa-dashboard-web/src/main/java/com/alipay/sofa/dashboard/controller/InstanceController.java
Labels: bug, cla:yes, size/S

#43 remove ZookeeperApplicationManager
  sofa-dashboard-backend/sofa-dashboard-arkmng/src/main/java/com/alipay/sofa/dashboard/application/ZookeeperApplicationManager.java
  sofa-dashboard-backend/sofa-dashboard-arkmng/src/main/java/com/alipay/sofa/dashboard/impl/ZkHelper.java
Labels: cla:yes, size/L
